### ISSUE TITLE
nonblocking ?

### ISSUE THREAD

**Issue by stuaxo** [tonysimpson/nanomsg-python#37]
Hi,
   Does this support nonblocking mode ?    I'm thinking of using PAIR with it ..

S

**Comment by vac** [comment]
I don't have much experience in using this library but making non-blocking BUS was not a problem!
I think that in PAIR it would be the same:
```python
    data = your_socket.recv(flags=nanomsg.DONTWAIT)
```
The only problem is that it raises exception instead of return None - so my code looks like this:
```python
    try:
        data = your_socket.recv(flags=nanomsg.DONTWAIT)
    except nanomsg.NanoMsgAPIError:
        data=None
```
If you want to detect proper exceptions that you have to check error codes of exception.

**Comment by stuaxo** [comment]
Cheers :)
